/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Omkar
 */
public class dbconnect extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dbconnect.class.getName());

    /**
     * Creates new form dbconnect
     */
    public dbconnect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("DISPLAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 110, 40));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "emp_id", "DeptID", "FirstName", "LastName", "Department", "Salary", "email", "Contact"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 320));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 120, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("REMOVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 120, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","omkar");
            java.sql.Statement st = con.createStatement();
        String query="select*from employee";
        ResultSet rs= st.executeQuery(query);
        ResultSetMetaData rsmd=rs.getMetaData();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int cols=rsmd.getColumnCount();
        String[] colName=new String[cols];
        for(int i=0;i<cols;i++)
        colName[i]=rsmd.getColumnName(i+1);
        model.setColumnIdentifiers(colName);
        String emp_id,DeptID,FirstName,LastName,Department,Salary,email,Contact;
        while(rs.next()){
            emp_id=rs.getString(1);
            DeptID=rs.getString(2);
            FirstName=rs.getString(3);
            LastName=rs.getString(4);
            Department=rs.getString(5);
            Salary=rs.getString(6);
            email=rs.getString(7);
            Contact=rs.getString(8);
            String[]row={emp_id,DeptID,FirstName,LastName,Department,Salary,email,Contact};
            model.addRow(row);
        }
        st.close();
        con.close();
        } catch (ClassNotFoundException ex) {
            System.getLogger(dbconnect.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (SQLException ex) {
            System.getLogger(dbconnect.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        menuframe m =new menuframe();
        m.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
int selectedRowIndex = jTable1.getSelectedRow();

if (selectedRowIndex == -1) {
    JOptionPane.showMessageDialog(null, "Please select a record to delete!");
    return;
}

try {
    // Assuming your first column (index 0) is the primary key 'id' or similar
    String id = model.getValueAt(selectedRowIndex, 0).toString();

    // Database connection
    Class.forName("com.mysql.cj.jdbc.Driver");
    java.sql.Connection con = java.sql.DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/mysql", "root", "omkar");

    // SQL delete query
    String sql = "DELETE FROM employee WHERE emp_id = ?";
    java.sql.PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1, id);

    int rowsAffected = pst.executeUpdate();

    if (rowsAffected > 0) {
        // Remove row from JTable
        model.removeRow(selectedRowIndex);
        JOptionPane.showMessageDialog(null, "Record deleted successfully!");
    } else {
        JOptionPane.showMessageDialog(null, "Failed to delete record from database!");
    }

    pst.close();
    con.close();

} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
}

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        try {
            //</editor-fold>
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","omkar");
            System.out.println("Connection Successful!"); 
    System.out.println(con);
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace(); 


        } catch (SQLException ex) {
             ex.printStackTrace(); 

        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dbconnect().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
