/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Omkar
 */
public class Depttable extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Depttable.class.getName());

    /**
     * Creates new form Depttable
     */
    public Depttable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DeptID", "DeptName", "DeptHead", "Location", "Budget"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("DISPLAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("REMOVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(92, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","omkar");
            java.sql.Statement st = con.createStatement();
        String query="select*from Department";
        ResultSet rs= st.executeQuery(query);
        ResultSetMetaData rsmd=rs.getMetaData();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int cols=rsmd.getColumnCount();
        String[] colName=new String[cols];
        for(int i=0;i<cols;i++)
        colName[i]=rsmd.getColumnName(i+1);
        model.setColumnIdentifiers(colName);
        String DeptID,DeptName,DeptHead,Location,Budget;
        while(rs.next()){
            DeptID=rs.getString(1);
           DeptName=rs.getString(2);
           DeptHead=rs.getString(3);
            Location=rs.getString(4);
            Budget=rs.getString(5);
            
            String[]row={DeptID,DeptName,DeptHead,Location,Budget};
            model.addRow(row);
        }
        st.close();
        con.close();
        } catch (ClassNotFoundException ex) {
            System.getLogger(dbconnect.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (SQLException ex) {
            System.getLogger(dbconnect.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
int selectedRowIndex = jTable1.getSelectedRow();

if (selectedRowIndex == -1) {
    JOptionPane.showMessageDialog(null, "Please select a record to delete!");
    return;
}

try {
    // Assuming your first column (index 0) is the primary key 'id' or similar
    String id = model.getValueAt(selectedRowIndex, 0).toString();

    // Database connection
    Class.forName("com.mysql.cj.jdbc.Driver");
    java.sql.Connection con = java.sql.DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/mysql", "root", "omkar");

    // SQL delete query
    String sql = "DELETE FROM Department WHERE DeptID = ?";
    java.sql.PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1, id);

    int rowsAffected = pst.executeUpdate();

    if (rowsAffected > 0) {
        // Remove row from JTable
        model.removeRow(selectedRowIndex);
        JOptionPane.showMessageDialog(null, "Record deleted successfully!");
    } else {
        JOptionPane.showMessageDialog(null, "Failed to delete record from database!");
    }

    pst.close();
    con.close();

} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
}

                                           
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        deptopt opt = new deptopt();
        opt.show();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        java.sql.Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/mysql","root","omkar"
        );
        System.out.println("Connection Successful!"); 
        System.out.println(con);
    } catch (ClassNotFoundException ex) {
        ex.printStackTrace(); 
    } catch (SQLException ex) {
        ex.printStackTrace(); 
    }

    // Display GUI
    java.awt.EventQueue.invokeLater(() -> new dbconnect().setVisible(true));
}

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
