/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import com.sun.jdi.connect.spi.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Omkar
 */
public class userform extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(userform.class.getName());

    /**
     * Creates new form userform
     */
    public userform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcancel = new javax.swing.JButton();
        jadd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfirst = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtlast = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtdep = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtsalary = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtcontact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtdept = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcancel.setText("CANCEL");
        jcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcancelActionPerformed(evt);
            }
        });
        getContentPane().add(jcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 90, 30));

        jadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jadd.setText("ADD");
        jadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddActionPerformed(evt);
            }
        });
        getContentPane().add(jadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 80, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ADD USER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 8, 293, 41));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("FIRST NAME:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jtfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfirstActionPerformed(evt);
            }
        });
        getContentPane().add(jtfirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("LAST NAME:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 70, -1, -1));

        jtlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtlastActionPerformed(evt);
            }
        });
        getContentPane().add(jtlast, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("DEPARTMENT:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 120, -1, -1));
        getContentPane().add(jtdep, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("SALARY:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        jtsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtsalaryActionPerformed(evt);
            }
        });
        getContentPane().add(jtsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 100, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("E-MAIL:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 176, -1, 10));

        jtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtemailActionPerformed(evt);
            }
        });
        getContentPane().add(jtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 100, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("CONTACT:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 171, -1, -1));

        jtcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcontactActionPerformed(evt);
            }
        });
        getContentPane().add(jtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 100, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Emp_id:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtidActionPerformed(evt);
            }
        });
        getContentPane().add(jtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("DeptID:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 215, -1, 20));

        jtdept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtdeptActionPerformed(evt);
            }
        });
        getContentPane().add(jtdept, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 80, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcancelActionPerformed
option op=new option();
op.show();
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jcancelActionPerformed

    private void jaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddActionPerformed
String Emp_id = jtid.getText();
String DeptID = jtdept.getText();
String FIRSTNAME = jtfirst.getText();
String LASTNAME = jtlast.getText();
String DEPARTMENT = jtdep.getText();
String SALARY = jtsalary.getText();
String EMAIL = jtemail.getText();
String CONTACT = jtcontact.getText();

if (Emp_id.isEmpty() || DeptID.isEmpty() || FIRSTNAME.isEmpty() || LASTNAME.isEmpty() ||
    DEPARTMENT.isEmpty() || SALARY.isEmpty() || EMAIL.isEmpty() || CONTACT.isEmpty()) {

    JOptionPane.showMessageDialog(null, "Some Field is Missing");

} else {
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        java.sql.Connection con = java.sql.DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/mysql", "root", "omkar"
        );

        String insertQuery = "INSERT INTO employee (emp_id, first_name, last_name, department, salary, email, contact, DeptID) "
                           + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        java.sql.PreparedStatement pst = con.prepareStatement(insertQuery);

        // Correct parameter mapping:
        pst.setDouble(1, Double.parseDouble(Emp_id));
        pst.setString(2, FIRSTNAME);
        pst.setString(3, LASTNAME);
        pst.setString(4, DEPARTMENT);
        pst.setDouble(5, Double.parseDouble(SALARY));
        pst.setString(6, EMAIL);
        pst.setString(7, CONTACT);
        pst.setDouble(8, Double.parseDouble(DeptID)); // Move DeptID to the correct place

        int rows = pst.executeUpdate();
        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "User added successfully!");
        }

        pst.close();
        con.close();
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }

    // Navigate back to menu
    menuframe menu = new menuframe();
    menu.show();
    dispose();
}

     // TODO add your handling code here:
    }//GEN-LAST:event_jaddActionPerformed

    private void jtlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtlastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtlastActionPerformed

    private void jtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtemailActionPerformed

    private void jtfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfirstActionPerformed

    private void jtsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtsalaryActionPerformed

    private void jtcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtcontactActionPerformed

    private void jtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtidActionPerformed

    private void jtdeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtdeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtdeptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new userform().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jadd;
    private javax.swing.JButton jcancel;
    private javax.swing.JTextField jtcontact;
    private javax.swing.JTextField jtdep;
    private javax.swing.JTextField jtdept;
    private javax.swing.JTextField jtemail;
    private javax.swing.JTextField jtfirst;
    private javax.swing.JTextField jtid;
    private javax.swing.JTextField jtlast;
    private javax.swing.JTextField jtsalary;
    // End of variables declaration//GEN-END:variables
}
